# Generated by Django 4.0.3 on 2022-04-10 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("accounts", "0002_rename_userprofuile_userprofile")]

    operations = [
        migrations.CreateModel(
            name="UserInterest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                ("normalized_name", models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="userprofile",
            name="interest",
            field=models.ManyToManyField(blank=True, to="accounts.userinterest"),
        ),
    ]
